node("ansible_docker"){
    stage("Git checkout"){
        git credentialsId: '4230dd89-d7a2-4ac5-9ce2-2b30fe9f25a1', url: 'https://github.com/OlegAnanyev/example-playbook.git'
    }
    stage("Prepare ssh key"){
        sh 'ansible-vault decrypt secret --vault-password-file vault_pass'
        sh 'mkdir ~/.ssh/ && mv ./secret ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa'
    }    
    stage("Install requirements"){
        sh 'ansible-galaxy install -r requirements.yml -p roles'
    }
    stage("Run playbook"){
        sh 'ansible-playbook site.yml -i inventory/prod.yml'      
    }
}
